### ISSUE TITLE
trying to install pencil code at my server and getting ERROR when run GRUNT

### ISSUE THREAD

**Issue by anapguerra** [PencilCode/pencilcode#231]
module.js:338
    throw err;
          ^
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/servercode4sis/code.4sis.com.br/public/pencilcode/node_modules/grunt-cli/node_modules/findup-sync/lib/findup-sync.js:15:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by anapguerra** [comment]
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/servercode4sis/code.4sis.com.br/public/pencilcode/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by dinukadesilva** [comment]
@anapguerra

this should be some thing wrong in the node_modules

1) Are u getting errors at the npm installation
2) what is your operating system

**Comment by anapguerra** [comment]
npm installation was ok.
I am trying to install it at DreamhostVPS
