### ISSUE TITLE
Something worng when run grunt

### ISSUE THREAD

**Issue by artinhuang** [PencilCode/pencilcode#248]
```
➜  pencilcode git:(master) grunt
Running "browserify:dist" (browserify) task
>> Bundle content/editor.js created.

Running "uglify:all" (uglify) task
{ [SyntaxError: Unexpected token: name (ArraySet)
  at JS_Parse_Error.get (<anonymous>:71:23)
  at formatError (internal/util/inspect.js:868:16)
  at formatRaw (internal/util/inspect.js:649:14)
  at formatValue (internal/util/inspect.js:544:10)
  at inspect (internal/util/inspect.js:194:10)
  at Object.formatWithOptions (util.js:84:12)
  at Console.(anonymous function) (console.js:196:15)
  at Console.log (console.js:207:31)
  at /Users/artin/dev/pencilcode/node_modules/_grunt-contrib-uglify@4.0.0@grunt-contrib-uglify/tasks/uglify.js:144:17
  at Array.forEach (<anonymous>:null:null)
  at Object.<anonymous> (/Users/artin/dev/pencilcode/node_modules/_grunt-contrib-uglify@4.0.0@grunt-contrib-uglify/tasks/uglify.js:78:16)
  at Object.<anonymous> (/Users/artin/dev/pencilcode/node_modules/_grunt@1.0.3@grunt/lib/grunt/task.js:252:15)
  at Object.thisTask.fn (/Users/artin/dev/pencilcode/node_modules/_grunt@1.0.3@grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/Users/artin/dev/pencilcode/node_modules/_grunt@1.0.3@grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Users/artin/dev/pencilcode/node_modules/_grunt@1.0.3@grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Users/artin/dev/pencilcode/node_modules/_grunt@1.0.3@grunt/lib/util/task.js:293:12)
  at /Users/artin/dev/pencilcode/node_modules/_grunt@1.0.3@grunt/lib/util/task.js:220:11
  at process.internalTickCallback (internal/process/next_tick.js:70:11)
]
  message: 'Unexpected token: name (ArraySet)',
  filename: 'editor.js',
  line: 131458,
  col: 6,
  pos: 4812384 }
>> Uglifying source content/editor.js failed.
Warning: Uglification failed.
Unexpected token: name (ArraySet).
Line 131458 in content/editor.js
 Use --force to continue.

Aborted due to warnings.
```

**Comment by zhuotianxiao** [comment]
该问题解决了吗
