### ISSUE TITLE
Save to and load from Google Drive

### ISSUE THREAD

**Issue by davidbau** [PencilCode/pencilcode#47]
To allow teachers to manage homework assignments without posting everything on the public web, we should be able to save and open and edit and run pencilcode programs on Google Drive.

I have registered pencilcode as an app with Google drive in a way that will allow us to develop on it.  Information to follow in this issue.

**Comment by coolyashish** [comment]
Hi,
I have worked on the google api's in the past. I have worked on the google drive, calendar, map, etc.  in my firstblaid application ( Link: https://github.com/coolyashish/Firstblaid ) .I would like to take on this bug. 
Can you please elaborate more on the requirements specifications. According to my learning from the description, I think we have a pencilcode program (file) and We need to save it on drive so that we can  open and edit it whenever needed. Please correct me If I am on the right track.

**Comment by davidbau** [comment]
The idea is to create a "Drive App" that lets you run Pencil Code in (or
from) Google Drive.

Here are other app examples:
https://developers.google.com/drive/web/examples/

The main requirements:
(1) Within GDrive, should associate an app (using the Pencil Code UI) with
a filetype like text/coffeescript, text/x-pencilcode, text/html
(2) The app should be able to load/save/create new files on Google Drive
while using pencil code as the UI for editing and running.
(3) We should ideally should be able to show "previews" of
text/x-pencilcode files within GDrive.
(4) Have a listing on the Chrome Web Store that allows users to easily
connect to Pencil Code as a GDrive app.

David

**Comment by coolyashish** [comment]
Hi David,
I have created a demo google drive app. Currently I am using oauth2.0 access for authorization. Anyone can go to this link and install pencilcode application as their drive application. Once it is done then any user is able to open or create a new file using pencilcode application ( a link should be there in the drive apps)

https://script.google.com/macros/s/AKfycbyUrUBH8Il1yx8KRcWXi5ulDugz1VKJwUhir_hDWYsRCFXa8A68/exec

Now, I will try to integerate it with pencilcode. I am new to pencilcode code structure. I have tried to install it on my local but facing some issues. I am behind proxy. I followed instruction from the github repo but on doing grunt I am getting an error [1] . Also if I did grunt devserver, It is redirecting me to our default proxy page. 

[1]
 79 passing (25s)
  1 failing

  1) proxy program should be able to access off-domain image bits:
     Uncaught Error: timeout
    at handletry (/home/ashish/pencilcode/test/lib/testutil.js:70:14)
    at /home/ashish/pencilcode/node_modules/node-phantom-simple/node-phantom-simple.js:40:26
    at IncomingMessage.<anonymous> (/home/ashish/pencilcode/node_modules/node-phantom-simple/node-phantom-simple.js:455:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)

**Comment by davidbau** [comment]
Don't worry about that test failure - it shows up after the whole build is
done and you're doing integration tests.  If you've gotten to that point,
the build works, and it's just an indication that you're on an atypical
network.

David

**Comment by coolyashish** [comment]
Ok,
But I am getting following error on localhost:8008
Logs:

ImmediateReturnError: Host localhost not part of domain pencilcode.net.dev ip:127.0.0.1 ua:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.120 Chrome/37.0.2062.120 Safari/537.36 url:/favicon.ico
ImmediateReturnError: Host localhost not part of domain pencilcode.net.dev ip:127.0.0.1 ua:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/37.0.2062.120 Chrome/37.0.2062.120 Safari/537.36 url:/favicon.ico

**Comment by davidbau** [comment]
Right.  Pencil code depends on the domain name looking correct (because the username is part of the domain name, like david.pencilcode.net).

So you need to start up chrome with a special flag so that it can resolve ".dev" domains to localhost.  In your chrome, you won't visit localhost:8008.  You'll visit http://pencilcode.net.dev/  - that's the purpose of the "devchrome" alias in the README.
